GEMINI_API_KEYS = ["AIzaSyAGhohqQbXerrCJTnOu1nPZTU4yxURawiM" ,  "AIzaSyBpLKfff5fzx8BSHGyTg-JCGmazpukNGFk" , "AIzaSyBsUBZyfUaqAtkSWgSNZXydqVS-YnomqiI" , "AIzaSyCUDs_USjzVfDCD8wwaVeqqj2BI0yRJKbw"]

[CHROMADB_CONFIG]
api_key = "ck-GgDLCLEeXKAEhpWCWMDwcFP1hEVH4gpqhii25vw98XSC"
tenant = "94df3293-175e-443f-994a-22655697ffc9"
database = "atlan"
